# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcrest', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
